# -*- coding: utf-8 -*-
"""Sample Code for GUI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hRhHYMoVPgVkcLmbHFi6DbjylLKSX4kv
"""

import PySimpleGUI as sg

sg.theme("Blue")
sg.set_options(font = ("Courier New", 12))

frame_1 = [[sg.Text('This is where you will write your story')], [sg.Text('Enter your story here !', size = (20,5)), sg.InputText()], [sg.Submit()], ]
frame_2 = [[sg.Text('This is where the image will be generated !')], ]

layout = [
    [sg.Frame('', frame_1, pad = (0,10)),
     sg.Frame('', frame_2, pad = (0, (14,5)), key = 'Hide')],
]

window = sg.Window('Image Generator', layout)
event, values = window.read()
window.close()

